version: '3'

services:

  db:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/

  adm:
    image: dpage/pgadmin4
    ports:
      - ${DBA_PORT}:80
    environment:
      - PGADMIN_DEFAULT_PASSWORD=${DBA_PASS}
      - PGADMIN_DEFAULT_EMAIL=${DBA_USER}
      - PGADMIN_PORT=${DBA_PORT}
    restart: always
    depends_on:
      - db

  app:
    build: ./
    ports:
      - ${APP_PORT}:80
    env_file:
      - .env
    restart: always
    depends_on:
      - db