CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ADMIN TABLES

CREATE TABLE roles (uuid UUID NOT NULL PRIMARY KEY, name VARCHAR(80) NOT NULL UNIQUE);

-- GENERAL TABLES

CREATE TABLE users (
  uuid UUID NOT NULL PRIMARY KEY,
  name VARCHAR(80) NOT NULL,
  username VARCHAR(80) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL,
  salt VARCHAR(200) NOT NULL,
  role_uuid UUID DEFAULT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (role_uuid) REFERENCES roles (uuid) ON DELETE CASCADE
);