version: '3'

services:

  db:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d/

  app:
    build: ./
    env_file:
      - .env
    restart: always
    depends_on:
      - db